### ISSUE TITLE
Link errors on Debian sid 

### ISSUE THREAD

**Issue by chrisburel** [woboq/moc-ng#6]
I'm using clang version 3.6.2, the binary download from clang's website, and Linux debian 4.2.0.  I'm using the downloaded clang binary to do the build.  I get the following error while linking:

    [  5%] Linking CXX executable moc
    cd /home/cburel/src/moc-ng/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/moc.dir/link.txt --verbose=1
    /home/cburel/apps/clang/bin/clang++      CMakeFiles/moc.dir/main.cpp.o CMakeFiles/moc.dir/mocng.cpp.o CMakeFiles/moc.dir/generator.cpp.o CMakeFiles/moc.dir/propertyparser.cpp.o CMakeFiles/moc.dir/mocppcallbacks.cpp.o CMakeFiles/moc.dir/mocastconsumer.cpp.o CMakeFiles/moc.dir/qbjs.cpp.o CMakeFiles/moc.dir/clangversionabstraction.cpp.o  -o moc -rdynamic -Wl,-Bstatic -lclangFrontend -lclangDriver -lclangCodeGen -lclangSema -lclangAnalysis -lclangRewrite -lclangAST -lclangParse -lclangLex -lclangBasic -lclangARCMigrate -lclangEdit -lclangFrontendTool -lclangRewrite -lclangSerialization -lclangTooling -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangStaticAnalyzerFrontend -lclangSema -Wl,-Bdynamic -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMBitWriter -lLLVMIRReader -lLLVMAsmParser -lLLVMR600CodeGen -lLLVMipo -lLLVMVectorize -lLLVMR600AsmParser -lLLVMR600Desc -lLLVMR600Info -lLLVMR600AsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMTableGen -lLLVMDebugInfo -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInstrumentation -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMScalarOpts -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMTarget -lLLVMMC -lLLVMCore -lLLVMSupport -L/home/cburel/apps/clang/lib -lpthread -ldl -lm -Wl,-Bstatic -lclangAnalysis -lclangRewrite -lclangAST -lclangParse -lclangLex -lclangBasic -lclangARCMigrate -lclangEdit -lclangFrontendTool -lclangSerialization -lclangTooling -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangStaticAnalyzerFrontend -Wl,-Bdynamic -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMBitWriter -lLLVMIRReader -lLLVMAsmParser -lLLVMR600CodeGen -lLLVMipo -lLLVMVectorize -lLLVMR600AsmParser -lLLVMR600Desc -lLLVMR600Info -lLLVMR600AsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMTableGen -lLLVMDebugInfo -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInstrumentation -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMScalarOpts -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMTarget -lLLVMMC -lLLVMCore -lLLVMSupport 
    CMakeFiles/moc.dir/main.cpp.o: In function `main':
    /home/cburel/src/moc-ng/src/main.cpp:366: undefined reference to `clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, clang::FrontendAction*, clang::FileManager*)'
    /home/cburel/src/moc-ng/src/main.cpp:373: undefined reference to `clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, clang::FrontendAction*, clang::FileManager*)'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    src/CMakeFiles/moc.dir/build.make:310: recipe for target 'src/moc' failed
    make[2]: *** [src/moc] Error 1                                                                                                                                                                                                                                             
    make[2]: Leaving directory '/home/cburel/src/moc-ng/build'                                                                                                                                                                                                                 
    CMakeFiles/Makefile2:87: recipe for target 'src/CMakeFiles/moc.dir/all' failed                                                                                                                                                                                             
    make[1]: *** [src/CMakeFiles/moc.dir/all] Error 2                                                                                                                                                                                                                          
    make[1]: Leaving directory '/home/cburel/src/moc-ng/build'                                                                                                                                                                                                                 
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by chrisburel** [comment]
Here's a comparison of the output of `nm -C` on the built main.cpp.o file from both Debian sid and Fedora 22:

    U clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, clang::FrontendAction*, clang::FileManager*)
    U clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::string, std::allocator<std::string> >, clang::FrontendAction*, clang::FileManager*)

For some reason Debian is writing out `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >` instead of just `std::string`.

**Comment by ogoffart** [comment]
I believe this has something to do with GCC 5 and it's new ABI.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

Libclang was probably compiled with the old ABI, but you are compiling mocng with the new ABI.
I guess because the libclang package were most likely build with GCC 4.x while you now have GCC 5 on your system.

Where did you get the clang packages?  was it from thedebian repository or from the llvm website?  Maybe using the packages from the debian repository might help.

Otherwise you can try  to add --disable-libstdcxx-dual-abi`:  Add this to the src/CMakeLists.txt
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  --disable-libstdcxx-dual-abi")
```

btw, what is the result of  `llvm-config --cxxflags` ?

**Comment by chrisburel** [comment]
I'm using the clang packages from [llvm website](http://llvm.org/releases/3.6.2/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-15.04.tar.xz).

* If I compile using the debian provided gcc/g++ 5.3.1, and build against the debian provided clang libraries, everything works.

* If I compile using the debian provided clang driver 3.6.2, and build against the debian provided clang libraries, I get link errors, although they are different than the ToolInvocation ones I posted initially.  These all appear to be methods that return `std::string`.  Here's the unique errors:

```
undefined references to `clang::QualType::getAsString(clang::PrintingPolicy const&) const' follow
undefined reference to `clang::DeclarationName::getAsString() const'
undefined reference to `clang::Lexer::getSpelling(clang::Token const&, clang::SourceManager const&, clang::LangOptions const&, bool*)'
undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
undefined reference to `clang::QualType::getAsString(clang::PrintingPolicy const&) const'
undefined reference to `clang::TypoCorrection::getAsString(clang::LangOptions const&) const'
```

* If I compile with the debian provided gcc 5.3.1, and build against the clang libraries from the llvm website, then I start to see `abi:cxx11` link errors.  These seem to be methods that return a `std::string`, or take one as an argument:

```
undefined references to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const' follow
undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
undefined reference to `clang::Lexer::getSpelling[abi:cxx11](clang::Token const&, clang::SourceManager const&, clang::LangOptions const&, bool*)'
undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
undefined reference to `clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, clang::FrontendAction*, clang::FileManager*)'
undefined reference to `clang::TypoCorrection::getAsString[abi:cxx11](clang::LangOptions const&) const'
```

  * Adding the `--disable-libstdcxx-dual-abi` to the CXX flags appears to not be supported by g++ (?)

```
[  5%] Building CXX object src/CMakeFiles/moc.dir/main.cpp.o
cd /home/cburel/src/moc-ng/build/src && /usr/bin/c++    -I/home/cburel/apps/clang-for-15.04/include -I/home/cburel/src/moc-ng/build/src  --disable-libstdcxx-dual-abi   -std=c++11 -g -Wall -fno-rtti  -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS  -o CMakeFiles/moc.dir/main.cpp.o -c /home/cburel/src/moc-ng/src/main.cpp
cc1plus: error: unknown pass libstdcxx-dual-abi specified in -fdisable
```
* If I compile with the debian provided clang driver, and build against the clang libraries from the llvm website, I get the same errors I posted initially.  The `clang` executable seems to also not support the `--disable-libstdcxx-dual-abi` (which makes sense, since it is related to the GCC 5 release).

Here's the output of `llvm-config --cxxflags` for both the debian-provided clang and the clang from the llvm website:
```
$ ~/apps/clang/bin/llvm-config --cxxflags
-I/home/cburel/apps/clang-for-15.04/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fPIC -ffunction-sections -fdata-sections -Wcast-qual
$ /usr/bin/llvm-config-3.6 --cxxflags
-I/usr/lib/llvm-3.6/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -ffunction-sections -fdata-sections -Wcast-qual
```

**Comment by chrisburel** [comment]
If I add `-D_GLIBCXX_USE_CXX11_ABI=0` to the defines list, then building with the clang driver works.  It definitely seems this is not a moc-ng issue, but a clang/gcc5 one.

**Comment by chrisburel** [comment]
Just for the record, [this stackoverflow qeustion](http://stackoverflow.com/questions/33368237/undefined-reference-in-clang-when-linking-to-a-library-compiled-with-gcc5) seems to be relevant, and seems to point to [an unresolved clang bug](https://llvm.org/bugs/show_bug.cgi?id=23529).
